version: "3.8"
services:
  php:
    build: ./php/
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public